// Curated models seeded into Firestore collection `curated_models`.
// Each entry MUST set every field consumed by CuratedModelRepository.kt
// (no backward compatibility — a missing field => the document is dropped at load time).
//
// Field reference:
//   hfRepoId          string  HF repo, e.g. "unsloth/gemma-3-4b-it-GGUF"
//   filename          string  exact .gguf file name in that repo
//   displayName       string  human-readable name shown on the card
//   provider          string  "unsloth" | "bartowski" | "lmstudio-community" | ...
//   paramsBillions    number  e.g. 4.0
//   paramsLabel       string  e.g. "4B"
//   quantization      string  e.g. "Q4_K_S"
//   fileSizeBytes     number  size of the .gguf in bytes
//   tags              array   free-form labels
//   notes             string  short description shown on the card (optional, may be "")
//   hasMmproj         bool    true if the same repo ships an mmproj-*.gguf for vision
//   minAppVersionCode number  app versionCode required to use this model

module.exports = [
  {
    hfRepoId: "unsloth/gemma-3-4b-it-GGUF",
    filename: "gemma-3-4b-it-Q4_K_S.gguf",
    displayName: "Gemma 3 4B Instruct",
    provider: "unsloth",
    paramsBillions: 4.0,
    paramsLabel: "4B",
    quantization: "Q4_K_S",
    fileSizeBytes: 2555504000,
    tags: ["gemma3", "vision", "multilingual", "instruct"],
    notes: "Gemma 3 4B Instruct, multimodal (vision via mmproj). 131K context.",
    hasMmproj: true,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/gemma-4-E4B-it-GGUF",
    filename: "gemma-4-E4B-it-Q3_K_S.gguf",
    displayName: "Gemma 4 E4B Instruct",
    provider: "unsloth",
    paramsBillions: 7.5,
    paramsLabel: "E4B",
    quantization: "Q3_K_S",
    fileSizeBytes: 4144700000,
    tags: ["gemma4", "vision", "any-to-any", "multilingual", "instruct"],
    notes: "Gemma 4 E4B Instruct (elastic 7.5B real footprint). Any-to-any multimodal. 131K context.",
    hasMmproj: true,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/gemma-4-E4B-it-GGUF",
    filename: "gemma-4-E4B-it-Q4_K_S.gguf",
    displayName: "Gemma 4 E4B Instruct",
    provider: "unsloth",
    paramsBillions: 7.5,
    paramsLabel: "E4B",
    quantization: "Q4_K_S",
    fileSizeBytes: 5196300000,
    tags: ["gemma4", "vision", "any-to-any", "multilingual", "instruct"],
    notes: "Gemma 4 E4B Instruct (elastic 7.5B real footprint). Any-to-any multimodal. 131K context.",
    hasMmproj: true,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/Qwen3-0.6B-GGUF",
    filename: "Qwen3-0.6B-Q4_K_M.gguf",
    displayName: "Qwen 3 0.6B",
    provider: "unsloth",
    paramsBillions: 0.6,
    paramsLabel: "0.6B",
    quantization: "Q4_K_M",
    fileSizeBytes: 396705472,
    tags: ["qwen3", "nano", "instruct"],
    notes: "Ultra-light Qwen 3 nano. Loads instantly, ideal for low-RAM devices.",
    hasMmproj: false,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/Qwen3.5-2B-GGUF",
    filename: "Qwen3.5-2B-Q4_K_M.gguf",
    displayName: "Qwen 3.5 2B",
    provider: "unsloth",
    paramsBillions: 2.0,
    paramsLabel: "2B",
    quantization: "Q4_K_M",
    fileSizeBytes: 1280835840,
    tags: ["qwen3.5", "vision", "any-to-any", "multilingual", "instruct"],
    notes: "Mobile sweet spot. Any-to-any multimodal (vision via mmproj).",
    hasMmproj: true,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/Qwen3-VL-4B-Instruct-GGUF",
    filename: "Qwen3-VL-4B-Instruct-Q4_K_M.gguf",
    displayName: "Qwen 3 VL 4B Instruct",
    provider: "unsloth",
    paramsBillions: 4.0,
    paramsLabel: "4B",
    quantization: "Q4_K_M",
    fileSizeBytes: 2497282336,
    tags: ["qwen3", "vision", "multimodal", "instruct"],
    notes: "Qwen 3 vision-language 4B. Lighter multimodal alternative to Gemma 3 4B.",
    hasMmproj: true,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/SmolLM3-3B-GGUF",
    filename: "SmolLM3-3B-Q4_K_M.gguf",
    displayName: "SmolLM3 3B",
    provider: "unsloth",
    paramsBillions: 3.0,
    paramsLabel: "3B",
    quantization: "Q4_K_M",
    fileSizeBytes: 1915306528,
    tags: ["smollm3", "edge", "instruct"],
    notes: "HuggingFace's edge-targeted 3B. Recent and efficient on low-power devices.",
    hasMmproj: false,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/Llama-3.2-1B-Instruct-GGUF",
    filename: "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
    displayName: "Llama 3.2 1B Instruct",
    provider: "unsloth",
    paramsBillions: 1.0,
    paramsLabel: "1B",
    quantization: "Q4_K_M",
    fileSizeBytes: 807694368,
    tags: ["llama3.2", "meta", "instruct"],
    notes: "Meta's mobile-targeted 1B. Strong general-purpose baseline.",
    hasMmproj: false,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "unsloth/Llama-3.2-3B-Instruct-GGUF",
    filename: "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
    displayName: "Llama 3.2 3B Instruct",
    provider: "unsloth",
    paramsBillions: 3.0,
    paramsLabel: "3B",
    quantization: "Q4_K_M",
    fileSizeBytes: 2019377600,
    tags: ["llama3.2", "meta", "instruct"],
    notes: "Meta's mid mobile 3B. Solid quality/size ratio for 2 GB budget.",
    hasMmproj: false,
    minAppVersionCode: 6,
  },
  {
    hfRepoId: "Jackrong/Qwen3.5-9B-DeepSeek-V4-Flash-GGUF",
    filename: "Qwen3.5-9B-DeepSeek-V4-Flash-Q3_K_M.gguf",
    displayName: "Qwen 3.5 9B DeepSeek V4 Flash",
    provider: "Jackrong",
    paramsBillions: 9.0,
    paramsLabel: "9B",
    quantization: "Q3_K_M",
    fileSizeBytes: 4623521024,
    tags: ["qwen3.5", "deepseek-distill", "vision", "reasoning", "long-context"],
    notes: "Qwen 3.5 9B fine-tuned with DeepSeek V4 Flash reasoning distillation. Multimodal (mmproj). 262K context. Heavy: ~5 GB RAM minimum. Reasoning always on (chat template hardcodes <think> — thinking toggle has no effect, but reasoning is auto-collapsed in the UI).",
    hasMmproj: true,
    minAppVersionCode: 6,
  },
];
